version: '3.8'

services:
  # 1. Base de datos: Almacena las métricas
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Limita el uso de RAM para que tu PC vaya fluido
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Visualización: El Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000" # Acceso en http://localhost:3001
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - elasticsearch

  # 3. Tu Aplicación: El puente entre FPGA y DB
  tfg_app:
    build: .
    container_name: tfg_app
    volumes:
      - .:/app # Permite que los cambios en tu código se vean sin reconstruir todo
    depends_on:
      elasticsearch:
        condition: service_healthy # No arranca la App hasta que la DB esté lista
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    # Mantiene el contenedor abierto incluso si hay errores
    stdin_open: true
    tty: true
    command: python main2.py