version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: es_tfg
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_tfg
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ./monitorización/datasource_elasticsearch.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./monitorización/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./monitorización/grafana.json:/var/lib/grafana/dashboards/port_counters.json
    depends_on:
      - elasticsearch

  api:
    build: .
    container_name: fast_api_tfg
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - MODE=simulation
      - ES_HOST=http://elasticsearch:9200
      - GRAFANA_URL=http://grafana:3000
      - GRAFANA_USER=admin
      - GRAFANA_PASS=admin
      - GRAFANA_EXTERNAL_URL=http://localhost:3001
    depends_on:
      - elasticsearch
      - grafana

  
  collector:
    build: .
    container_name: collector
    command: python data_collector.py
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api

