FROM python:3.11-slim

WORKDIR /app

# Instalamos las dependencias

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos todo el proyecto
COPY . .

# Ejecutamos tu script principal
CMD ["bash"]